### ISSUE TITLE
Strip alignment and re-merge when user click save

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-editor#14]
TBD: what do if alignment is broken?

**Comment by elsylambert** [comment]
@larsgson Can you suggest how this can be tested?

**Comment by larsgson** [comment]
> @larsgson Can you suggest how this can be tested?

@elsylambert I have now worked on a button to indicate what goes on here - and also to list the words, once they have broken alignments. This is now part of the branch Abel is doing some more work with (for search & replace)
So actually the best approach for testing this I would see is; to note it down and then test it later, once we have this new upcoming branch merged

**Comment by larsgson** [comment]
@elsylambert I think this issue has been solved and this can now be closed

**Comment by elsylambert** [comment]
When alignment is broken, the indicator shows on the menu icons and lists the broken alignments. Looks good.
