### ISSUE TITLE
Suggestion: The toolbar - do not let it scroll off visible area

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-editor#25]
at present the buttons on the toolbar scroll with the text. I think they should remain visible and clickable.

**Comment by elsylambert** [comment]
Tool bar stays visible when text is scrolled.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Tool bar stays visible when scrolling.
