### ISSUE TITLE
Search and Replace in a single book. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/uw-editor#29]
Issue:
---

DoD: 
---
Users can search and replace for regex or multiple words, and see the results. 

Details:
---

**Comment by birchamp** [comment]
@birchamp add DoD to this ^^^^^

**Comment by abelpz** [comment]
This has been added to oce-editor-tools

**Comment by elsylambert** [comment]
@abelpz v1.0.0 build 79e998c QA Search works fine, but when I try to replace it duplicates all the words as in the screenshot:
<img width="986" alt="Screenshot 2023-09-12 at 9 20 27 AM" src="https://github.com/unfoldingWord/uw-editor/assets/51806180/48010944-f33f-4b85-bf88-6bf15aba7a81">

**Comment by abelpz** [comment]
Looks like an old error coming back. I will look into it.

**Comment by elsylambert** [comment]
@theNerd247 Can you take a look at this issue?

**Comment by theNerd247** [comment]
Sure thing!

**Comment by theNerd247** [comment]
Trail markers for solving the problem: 

I can replicate the issue in gateway translate. It appears that the replace button is not idempotent; every time the replace button is pressed every word in the original text is duplicated. This is independent of the book being used (tested on Titus and Ruth)

**Comment by danielklapp** [comment]
Search and Replace is working properly. Looks good in v1.0.0 build 93e07b3 QA.

<img width="753" alt="Screenshot 2023-09-22 at 9 34 07 AM" src="https://github.com/unfoldingWord/uw-editor/assets/82067076/55fa869c-de23-47d4-916e-ec437b01494f">

**Comment by elsylambert** [comment]
Verified on  https://develop--gateway-translate.netlify.app/ with v1.0.0 build 0168902 QA. Search and Replace looks good and works as expected. Not seeing duplication of words on Replacing the word.
