### ISSUE TITLE
Chapter Sequence is rendered incorrectly 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/uw-editor#30]
Title and Introduction is showing chapter 1 and chapter 1 link shows chapter 2 and so on.
![Screen Shot 2022-10-31 at 1.34.19 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f177145b-6a9a-4fc9-b341-b3f549b96544)

**Comment by mandolyte** [comment]
@abelpz @larsgson could this be a data issue (how the usfm is constructed)? It doesn't seem to be consistent

**Comment by abelpz** [comment]
Is this happening for one specific resource? I believe when I tried this for other resources it worked fine, it might be because of the usfm, I'd have to look at a working-as-expected usfm and perf and compare with this one.

**Comment by mandolyte** [comment]
Confirmed that this is a data issue (or possibly a PK issue).

The lines at the beginning of the text are:
```
\ts\*
\c 1
\p
```

If you swap the chapter heading with the line before it, it works as it should:
```
\c 1
\ts\*
\p
```

**Comment by mandolyte** [comment]
Confirmed a data problem. See:
https://unfoldingword.zulipchat.com/#narrow/stream/207526-Tools---UR/topic/USFM.20for.20Titus/near/315634624

**Comment by mandolyte** [comment]
After further discussion (see the link to zulip above), it seems like this needs to be worked on.

_As a work around, the file can be saved which will re-order the tags so that it displays correctly._

**Comment by elsylambert** [comment]
Verified in the latest build. Chapter sequence works fine from chapter 1 to 9 and after that the title shows the chapter 1 for 11 to 19 and chapter 2 for 20 to 29 and so forth. 
<img width="1381" alt="Screenshot 2023-01-17 at 9 45 13 AM" src="https://user-images.githubusercontent.com/51806180/212929058-f5fab4b6-fc5e-4fc7-8ce6-71f03fb36732.png">

**Comment by elsylambert** [comment]
https://user-images.githubusercontent.com/51806180/212929664-fa7082a3-df4e-4b3c-a010-fe1566a353b5.mov

**Comment by elsylambert** [comment]
Chapter sequence is rendered correctly in v0.0.20 build 57657df.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Looks good
