### ISSUE TITLE
Backspace and delete key do not enable the save button

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/uw-editor#31]
v0.0.9 build 09f2ea9 QA
The backspace and delete key do not enable the save (but they do enable the undo).
Note:Forward delete works(fn+delete)

**Comment by mandolyte** [comment]
I was unable to duplicate this today. Of course, I had to click away (blur) before the button was enabled.

@elsylambert

**Comment by elsylambert** [comment]
@mandolyte I see the Reverse of the comment that I made for this issue. Delete and backspace now works but Forward delete does not. So now save button is not enabled when forward delete is done.

**Comment by mandolyte** [comment]
What is a forward delete? Is that a Mac os thing? What does it do? How is
it different than a delete, which deletes the character following the
cursor?

**Comment by elsylambert** [comment]
@mandolyte Forward delete is (Fn+Delete) on Mac, which is the same as Delete on windows keyboard. The DELETE button on Mac acts like a Backspace button on windows(Backward delete).

**Comment by elsylambert** [comment]
Not seeing this problem in v0.0.18 build cc1f350. Delete and forward delete works fine and enables the Save button.
