### ISSUE TITLE
Font size of Title is too big that it overlaps when the book name is longer

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/uw-editor#32]
![Screen Shot 2022-10-31 at 3.18.26 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2c9e75d4-b43e-43fc-abfc-269ad412f78d)

**Comment by elsylambert** [comment]
Looks good in v0.0.19 build 4fbaf1a
<img width="1381" alt="Screenshot 2023-01-17 at 9 56 49 AM" src="https://user-images.githubusercontent.com/51806180/212932017-097f1e5d-0db2-46f5-b2c7-de6a7c2b87bb.png">

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Looks good
