### ISSUE TITLE
Undo/Redo is not enabled when text is changed sometimes 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/uw-editor#33]
undo/redo should sometimes enable the save button since they result in a text different that last saved; but it isn't working when it should

**Comment by mandolyte** [comment]
I cannot replicate this now. It may have been fixed with the state change improvements that Lars did. I'll label retest and move to QA App.

**Comment by elsylambert** [comment]
Not seeing this problem in v0.0.18 build cc1f350.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Working properly
