### ISSUE TITLE
add reference column to search results

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/uw-editor#43]

**Comment by abelpz** [comment]
This has been added to findr and oce-editor-tools

**Comment by elsylambert** [comment]
Looks good in v1.0.0 build 79e998c QA
<img width="615" alt="Screenshot 2023-09-12 at 9 45 48 AM" src="https://github.com/unfoldingWord/uw-editor/assets/51806180/a63beb71-d251-4e5c-9948-da94672a3a96">

**Comment by danielklapp** [comment]
There is a reference column to search results. Tested with v1.0.0 build 79e998c QA. Looks good to me. 

<img width="790" alt="Screenshot 2023-09-13 at 11 20 04 AM" src="https://github.com/unfoldingWord/uw-editor/assets/82067076/d260d5ca-0628-415e-8826-a675f34e7365">
