### ISSUE TITLE
Not able to open the same book again

### ISSUE THREAD

**Issue by Joel-C-Johnson** [unfoldingWord/uw-editor#44]
Steps:
1. log in to the app.
2. Open/Add a book.
3. Open/Add the same book again. 
4. You will get a black card.

Note: are we expecting the same book shown in two cards if we add the same book twice?

**Comment by larsgson** [comment]
I will look into this together with this issue:
https://github.com/unfoldingWord/uw-editor/issues/40

**Comment by elsylambert** [comment]
Looks good in v0.0.18 build cc1f350. When user tries to open a book which is already open in a card, then a pop-up is shown at the bottom of screen that the "Book is already open", hence preventing the users to open multiple cards with the same book.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Looks good
