### ISSUE TITLE
Undo/Redo do not disable/enable the Save button

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/uw-editor#54]
v0.0.18 build cc1f350 
- Edit a text on the card and click on Save button.
- Note that the undo button is enabled. Click on Undo to revert the changes.
- The changes are reverted but the Save button is not enabled.

- Now, click on Redo button, the edits are back again.
- Note that the Save button is not enabled.

**Comment by birchamp** [comment]
This issue now includes the situation outlined in #48

**Comment by elsylambert** [comment]
Undo/Redo works fine and the Save button is enabled/disabled accordingly in v0.0.19 build 4fbaf1a.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Working properly
