### ISSUE TITLE
After Editing a Graft, words in the main text are duplicated 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/uw-editor#56]
Steps to replicate:
- Open a card, e.g Titus.
- Click on the title Titus, it opens a small Edit box "Edit the Graft".
- Add some character and click on Done. Note that you can see the changes in the Title.
- Edit the graft again and remove the Character added in the previous step and click Done.
- Note that the main text has every word duplicated as shown in the screenshot below:![Screenshot 2023-01-03 at 9.17.56 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ccfb57a5-efa7-4184-abbe-e0170f34651b)
- This is iterative and the words multiplies.
![Screenshot 2023-01-03 at 9.18.56 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/5626e384-42df-4cd2-a2ea-cd6e41e40796)

**Comment by elsylambert** [comment]
@mandolyte This issue is for words duplication.

**Comment by superdav42** [comment]
Looks to be an issue with epitelete see discussion https://discord.com/channels/867746700390563850/1019275909183836251/1069783444499996813
