### ISSUE TITLE
If a book with changes is closed and re-opened, the save icon is not enabled

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-editor#67]
Steps:

1. open a book
2. make changes
3. close the card by clicking the "X" in upper right
4. if a warning appears, just click continue to allow to close
5. re-open the book

Observe:
- the changes are still there (not lost)
- the save button is **not** enabled
- however, the undo button **is** enabled (therefore it knows it has changed)

As a workaround, you can click the undo and then redo. Then the save will be enabled.

**Comment by larsgson** [comment]
The state of "save button disabled" and "undo enabled" is a valid combination. 
I see no way of knowing that somebody previously closed a card without saving and now returns back - compared to the valid combination above. So there is a need to have more information before this can be solved.

#### I see these two alternatives:
- seed the Editor with a hasUnsavedData boolean as a prop parameter _(like already kept in gT)_
- provide actions: saveData and undo/redo to trigger this programatically from the app _(like trigger this from gT)_

**Comment by larsgson** [comment]
Hmm, @birch - so this might not be solved in just a day, since there will be a need to adapt **both** uw-editor and gT in order to get this working. Can we maybe note this as an issue to be solved in v 1.0?

**Comment by elsylambert** [comment]
Works as expected in v0.1.0 build 9d538e4 QA. If a book is closed without saving, then upon re-opening the card, edits are not lost and the Save button is enabled. Users are then able to either Save or undo the changes.

**Comment by elsylambert** [comment]
Wrote up https://github.com/unfoldingWord/gateway-translate/issues/142 separately for Save button.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Everything is working properly.
