### ISSUE TITLE
Save button and undo state is lost when closing and reopening a gT card

### ISSUE THREAD

**Issue by larsgson** [unfoldingWord/uw-editor#70]
Keeping these states only internally is not enough for having a consistent behavior, when re-opening a new (cached) Epitelete-html. Both undoInx and lastSaveUndoInx need to be kept externally from uw-editor.

**Comment by elsylambert** [comment]
Save, undo and Redo functions are working fine when a card is closed and reopened in v0.3.0 build cf4f0aa.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Everything looks good
