### ISSUE TITLE
Bible Reference - unwanted scrolling

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-editor#74]
If you have three books open and click on a verse in one of the first two, the workspace will scroll to the third book.

**Comment by larsgson** [comment]
This issue was solved partly in the updated oce-editor-tools (partly by making use of Sam's code) and partly internally for gT in PR #191

**Comment by elsylambert** [comment]
Not seeing this issue in v1.0.0 build 79e998c QA.

**Comment by danielklapp** [comment]
Looks good to me. Not seeing unwanted scrolling. Tested with v1.0.0 build 79e998c QA.
